### ISSUE TITLE
img2pdf errors out when book PNGs are malformed

### ISSUE THREAD

**Issue by NlckN4me** [devnoname120/google-play-book-downloader#24]
C:\Users\User\Downloads\Compressed\google-play-book-downloader-main>poetry run play-book-pdf-build books/hw4XEQAAQBAJ
[INFO] the manifest indicates that the book pages are ordered right to left. We will swap the order of the pages so that they show correctly in the PDF.
Merging 213 pages... (this can take a long time)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\User\Downloads\Compressed\google-play-book-downloader-main\play_book_pdf_tool\play_book_pdf_tool.py", line 63, in pdf_generate
    create_pdf(page_paths, tmp_pdf)
  File "C:\Users\User\Downloads\Compressed\google-play-book-downloader-main\play_book_pdf_tool\play_book_pdf_tool.py", line 89, in create_pdf
    img2pdf.convert(*image_paths, outputstream=output_pdf)
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\img2pdf.py", line 2360, in convert
    ) in read_images(
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\img2pdf.py", line 1682, in read_images
    pngidat, palette = parse_png(rawdata)
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-sdJNAun_-py3.8\lib\site-packages\img2pdf.py", line 1526, in parse_png
    raise Exception("invalid png: %d %d %d" % (i, n, len(rawdata)))
Exception: invalid png: 7037 185273099 7040

I downgraded python version to version 3.8 and successfully did poetry install. However, the above error occurs when I build a pdf.

I tried upgrading the library, but it failed. None of the downloaded files were 0 bytes.

jpeg file and png file are mixed. Is this the cause of the problem?

**Comment by NlckN4me** [comment]
I think there is an error in create_pdf function, but I don't know how to fix it.

**Comment by devnoname120** [comment]
@NlckN4me @VergeDX Can you guys send me the faulty PNG via email? You can find it on my GitHub profile

**Comment by devnoname120** [comment]
No update so I’m closing the issue
