### ISSUE TITLE
Error: Failed to extract the encoded decryption key from Play Book Reader's HTML body:

### ISSUE THREAD

**Issue by dragonxtek** [devnoname120/google-play-book-downloader#3]
Why the request doesn't works?
Here is the response for zx google-play-book-downloader.mjs 

```
[ksxPDwAAQBAJ] Script started
Error: Failed to extract the encoded decryption key from Play Book Reader's HTML body: <html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 405 (Bad Request)!!1</title><style nonce="j_pC8dvNeUoocN6kVc8uwA">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><main id="af-error-container" role="main"><a href=//www.google.com><span id=logo aria-label=Google role=img></span></a><p><b>405.</b> <ins>That’s an error.</ins><p>The server cannot process the request because it is malformed. It should not be retried. <ins>That’s all we know.</ins></main>
    at extract_decryption_key (file:///tmp/google-play-book-downloader/google-play-book-downloader.mjs:204:11)
    at file:///tmp/google-play-book-downloader/google-play-book-downloader.mjs:52:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError: Cannot read properties of null (reading '1')
      at extract_decryption_key (file:///tmp/google-play-book-downloader/google-play-book-downloader.mjs:202:101)
      at file:///tmp/google-play-book-downloader/google-play-book-downloader.mjs:52:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by devnoname120** [comment]
@VergeDX Cool find! Yes, turns out that knock ([mirror](https://github.com/thatsysadminforks/knock)) — recommended in your link — is just a 100-line C++ wrapper that literally [doesn't do anything else](https://github.com/thatsysadminforks/knock/blob/0aa4005fd4f2ee1b41c20643017c8f0a2bdf6262/src/knock.cpp#L1) than calling [libgourou](https://forge.soutade.fr/soutade/libgourou).

Note that libgourou has an (unofficial) docker container that should make it easier to run: https://github.com/bcliang/docker-libgourou

Contrary to the Calibre [DeDRM](https://github.com/noDRM/DeDRM_tools) plugin it doesn't need the Adobe Digital Editions (ADE) software to run. It's also a lot more convenient to use.

-------------

I just noticed that it isn't written in the README but whenever the PDF is available for export in Google Play Books through an ACSM file you should use that instead. My script is only meant for books that can't be exported at all, or those where the ACSM export is really low quality (scanned books usually). Likewise for the experimental EPUB downloader available in the repository.
